In [1]:
import tensorflow as tf
vector1 = tf.constant([2.0, 3.0, 4.0])
print(vector1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)

In [2]:
vector2 = tf.constant([3.0, 4.0, 5.0])
print(vector2)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float32)

In [3]:
print(tf.add(vector1,vector2))

tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)

In [4]:
print(vector1*vector2)

tf.Tensor([ 6. 12. 20.], shape=(3,), dtype=float32)

In [5]:
print(tf.tensordot(vector1,vector2,axes=1))

tf.Tensor(38.0, shape=(), dtype=float32)

In [6]:
a = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
b = tf.constant([1., 2., 3.])
c = tf.tensordot(a, b, axes=1)
print(c)

tf.Tensor([14. 32. 50.], shape=(3,), dtype=float32)

In [7]:
from google.colab import files
uploaded = files.upload()

Saving concrete_data_sample.csv to concrete_data_sample.csv

In [13]:
data = pd.read_csv('concrete_data_sample.csv')
import pandas as pd
import numpy as np
data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [12]:
data.shape

(10, 9)

In [14]:
data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,10.000000,10.000000,10.0,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,371.060000,83.540000,0.0,205.400000,0.500000,972.040000,649.050000,159.000000,47.982000
std,116.826664,59.995318,0.0,30.302915,1.054093,55.820092,73.254674,159.220323,13.213437
min,198.600000,0.000000,0.0,162.000000,0.000000,932.000000,594.000000,28.000000,36.450000
25%,282.625000,23.750000,0.0,175.500000,0.000000,932.000000,594.000000,28.000000,40.465000
50%,356.250000,104.500000,0.0,228.000000,0.000000,932.000000,633.500000,59.000000,44.000000
75%,451.250000,127.800000,0.0,228.000000,0.000000,1024.600000,674.500000,337.500000,46.735000
max,540.000000,142.500000,0.0,228.000000,2.500000,1055.000000,825.500000,365.000000,79.990000

In [15]:
data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [16]:
data_columns = data.columns
predictors = data[data_columns[data_columns != 'Strength']]
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [17]:
target = data['Strength']
pre_norms = (predictors - predictors.mean() / predictors.std())
pre_norms.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,536.823842,-1.392442,NaN,155.221774,2.025658,1022.586199,667.139814,27.001384
1,536.823842,-1.392442,NaN,155.221774,2.025658,1037.586199,667.139814,27.001384
2,329.323842,141.107558,NaN,221.221774,-0.474342,914.586199,585.139814,269.001384
3,329.323842,141.107558,NaN,221.221774,-0.474342,914.586199,585.139814,364.001384
4,195.423842,131.007558,NaN,185.221774,-0.474342,960.986199,816.639814,359.001384

In [18]:
n_cols = pre_norms.shape[1]
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
def regression():
    model = Sequential()
    model.add(Dense(50, activation='relu', input_shape = (n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer ='adam', loss='mean_squared_error')
    return model
model = regression()
model.fit(pre_norms, target, validation_split=.3, epochs=25, verbose=2)

Epoch 1/25

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 - 2s - 2s/step - loss: nan - val_loss: nan
Epoch 2/25
1/1 - 0s - 372ms/step - loss: nan - val_loss: nan
Epoch 3/25
1/1 - 0s - 90ms/step - loss: nan - val_loss: nan
Epoch 4/25
1/1 - 0s - 94ms/step - loss: nan - val_loss: nan
Epoch 5/25
1/1 - 0s - 176ms/step - loss: nan - val_loss: nan
Epoch 6/25
1/1 - 0s - 99ms/step - loss: nan - val_loss: nan
Epoch 7/25
1/1 - 0s - 87ms/step - loss: nan - val_loss: nan
Epoch 8/25
1/1 - 0s - 214ms/step - loss: nan - val_loss: nan
Epoch 9/25
1/1 - 0s - 140ms/step - loss: nan - val_loss: nan
Epoch 10/25
1/1 - 0s - 132ms/step - loss: nan - val_loss: nan
Epoch 11/25
1/1 - 0s - 158ms/step - loss: nan - val_loss: nan
Epoch 12/25
1/1 - 0s - 128ms/step - loss: nan - val_loss: nan
Epoch 13/25
1/1 - 0s - 125ms/step - loss: nan - val_loss: nan
Epoch 14/25
1/1 - 0s - 145ms/step - loss: nan - val_loss: nan
Epoch 15/25
1/1 - 0s - 146ms/step - loss: nan - val_loss: nan
Epoch 16/25
1/1 - 0s - 166ms/step - loss: nan - val_loss: nan
Epoch 17/25
1/1 - 0s - 126ms/step - loss: nan - val_loss: nan
Epoch 18/25
1/1 - 0s - 131ms/step - loss: nan - val_loss: nan
Epoch 19/25
1/1 - 0s - 169ms/step - loss: nan - val_loss: nan
Epoch 20/25
1/1 - 0s - 167ms/step - loss: nan - val_loss: nan
Epoch 21/25
1/1 - 0s - 300ms/step - loss: nan - val_loss: nan
Epoch 22/25
1/1 - 0s - 139ms/step - loss: nan - val_loss: nan
Epoch 23/25
1/1 - 0s - 90ms/step - loss: nan - val_loss: nan
Epoch 24/25
1/1 - 0s - 88ms/step - loss: nan - val_loss: nan
Epoch 25/25
1/1 - 0s - 145ms/step - loss: nan - val_loss: nan